lib: add own bpf_common.h to fix builds on distros without
Building natively, arm64 debian 8 doesn't put bpf_common.h in its
linux-libc-dev package, so get it from linux and put it in a new
directory per_event_tests/include/linux:

mkdir include/linux; cp ...linux/include/uapi/linux/bpf_common.h include/linux

so the native build picks it up.

Fixes:

gcc -Wall -O2 -I../include  -c -o test_utils.o test_utils.c
In file included from bpf_helpers.c:10:0:
../include/bpf.h:11:30: fatal error: linux/bpf_common.h: No such file or directory
 #include <linux/bpf_common.h>
                              ^
compilation terminated.
<builtin>: recipe for target 'bpf_helpers.o' failed
make[1]: *** [bpf_helpers.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/kim/perf_event_tests/lib'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

Signed-off-by: Kim Phillips <kim.phillips@arm.com>